show the errors

diff --git a/bin.homelink/envup b/bin.homelink/envup
--- a/bin.homelink/envup
+++ b/bin.homelink/envup
@@ -302,9 +302,10 @@ rust_up() {
 
 [[ $ZSH_EVAL_CONTEXT =~ :file$ ]] && sourced=1 || sourced=0
 if [[ $sourced -ne 1 ]]; then
-    nc -z www.apple.com 80 -G1 2> /dev/null
-    if [ $? -ne 0 ]; then
+    ic_output=$(nc -z www.apple.com 80 -G1 2>&1); ic_status=$?
+    if [ $ic_status -ne 0 ]; then
         echo "  😣 Doesn't look like there's a connection to the internet right now..."
+        echo "     Error: $ic_output"
         exit 1
     fi
 
